Create header component
praktikum-game/defence-game pull request #10
Opened 2021-11-10 08:46 UTC by Verisana

Создал тут компонент `Header`, но по пути еще работал с этими вещами:
- добавил рбаотающий прекоммит. Теперь код не коммитится без предварительной проверки
- исправил ошибки `stylelint`
- пытался настроить правила по БЭМ, чтобы помечал, но ничего не вышло. Не могу избавиться от ошибок, если включить плагин: `stylelint-selector-bem-pattern`. Чтобы он включился, надо в файле с компонентами добавить: `/** @define ComponentName */`. Я подозреваю, что проблема с паттерном

Когда вольем эти компоненты, можно будет собрать уже простые страницы. Чувствую, нам нужно быстрее вливать изменения, иначе много несостыковок придется править

2021-11-10 08:46 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создать компоненту Header](https://trello.com/c/xY3Y9VE6/37-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%83-header)

2021-11-10 09:19 UTC, diglibum approved these changes

2021-11-10 11:30 UTC, ShvetsovYura approved these changes
У меня замечаний нет

2021-11-10 11:30 UTC, ShvetsovYura commented on .stylelintrc.json
> +      "componentSelectors": "^\\.{componentName}(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:(?:_|--)[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*){0,2}(?:\\[.+\\])?$"
А что это за такая забористая регулякрка?

2021-11-10 12:06 UTC, Verisana commented on .stylelintrc.json
> +      "componentSelectors": "^\\.{componentName}(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:(?:_|--)[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*){0,2}(?:\\[.+\\])?$"
Это вот и есть попытка подключить правила для БЭМ. Они сейчас выключены. Проверка не работает. В принципе, можно выпилить. Но нужно будет иметь в виду, что у нас нет проверки названия css-классов

Собрана по мотивам:
https://github.com/postcss/postcss-bem-linter

https://github.com/postcss/postcss-bem-linter/blob/master/lib/preset-patterns.js
```javascript
function bemSelector(block, presetOptions) {
  const ns =
    presetOptions && presetOptions.namespace
      ? `${presetOptions.namespace}-`
      : '';
  const WORD = '[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*';
  const element = `(?:__${WORD})?`;
  const modifier = `(?:(?:_|--)${WORD}){0,2}`;
  const attribute = '(?:\\[.+\\])?';
  return new RegExp(`^\\.${ns}${block}${element}${modifier}${attribute}$`);
}
```

2021-11-10 16:03 UTC, bercly0b requested changes

2021-11-10 16:03 UTC, bercly0b commented on src/components/ContainerHeader/ContainerHeader.tsx
> +export const ContainerHeader = ({ children, ...otherProps }: ContainerHeaderProps): JSX.Element => (
тоже не очень понимаю назначение этого компонента. 
он нужен только что бы поставить `background-color: yellow;` ?

2021-11-10 16:03 UTC, bercly0b commented on src/components/ContainerHeader/ContainerHeader.tsx
> +export const ContainerHeader = ({ children, ...otherProps }: ContainerHeaderProps): JSX.Element => (
если это хедер для всей страницы, то давай его назовем просто `Header`, без префикса `Container`

2021-11-11 03:59 UTC, Verisana commented on src/components/ContainerHeader/ContainerHeader.tsx
> +export const ContainerHeader = ({ children, ...otherProps }: ContainerHeaderProps): JSX.Element => (
Это для `PageContainer`. Но, наверное, можно его обобщить на всю страницу, если нужно будет. Я тут пока стили особо не писал. Это будет зеленькая полоска, если смотреть по макетам.

2021-11-11 08:54 UTC, Verisana commented on .stylelintrc.json
> +      "componentSelectors": "^\\.{componentName}(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:(?:_|--)[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*){0,2}(?:\\[.+\\])?$"
Чтобы никого не смущать, убрал этот плагин :)

2021-11-11 13:59 UTC, bercly0b commented on src/components/ContainerHeader/ContainerHeader.tsx
> +export const ContainerHeader = ({ children, ...otherProps }: ContainerHeaderProps): JSX.Element => (
давай обобщим тогда.
компонент должен инкапсулировать какую то логику. а тут пока я не понял какая в нем логика

2021-11-11 15:33 UTC, Verisana commented on src/components/ContainerHeader/ContainerHeader.tsx
> +export const ContainerHeader = ({ children, ...otherProps }: ContainerHeaderProps): JSX.Element => (
Фактически там будут сидеть навигационные кнопки, как в обычном `Header`. В общем, переименовал его.

2021-11-12 10:22 UTC, bercly0b approved these changes

2021-11-12 11:23 UTC, merged