feat: create new Title component
praktikum-game/defence-game pull request #11
Opened 2021-11-10 11:54 UTC by Verisana

Создан `Title` компонент. Тут главное, что в зависимости от параметра, он меняет свой тэг и размер. Насколько мне видится, никаких других возможностей от него нам не надо.

2021-11-10 11:54 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Написать Title компоненту](https://trello.com/c/T5R8O1lL/40-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-title-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%83)

2021-11-10 13:45 UTC, diglibum approved these changes

2021-11-10 15:15 UTC, Verisana commented on src/components/Title/Title.tsx
> +export const Title = ({ headingLevel = 1, ...otherProps }: TitleProps): JSX.Element => {
Добавил новый пропс `align`, которым можно поменять позиционирование. Тут, правда, раз нет плагинов, не смог воспользоваться `&_` штучками.

2021-11-10 15:17 UTC, ShvetsovYura approved these changes

2021-11-10 16:04 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  headingLevel = 1,
я бы по дефолту сделал не 1, а 5 или 6, потому что h1 должен быть только один на странице..

2021-11-10 16:06 UTC, bercly0b requested changes

2021-11-10 16:06 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  return <CustomHeading className={`title title_${align}`} {...otherProps}></CustomHeading>;
`<CustomHeading className={`title title_${align}`} {...otherProps} />`

и по неймингу немного попридираюсь.
компонент называется `Title`, а вложенный `CustomHeading`, немного путает.
я бы переименовал CustomHeading в CustomTitle или просто в Component

2021-11-10 16:06 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  return <CustomHeading className={`title title_${align}`} {...otherProps}></CustomHeading>;
и еще было бы здорово если бы в этот компонент можно было с наружи передать className и снаружи описать стили для этого класса

2021-11-11 08:57 UTC, Verisana commented on src/components/Title/Title.tsx
> +  headingLevel = 1,
Исправил

2021-11-11 09:00 UTC, Verisana commented on src/components/Title/Title.tsx
> +  return <CustomHeading className={`title title_${align}`} {...otherProps}></CustomHeading>;
Название поменял на `Component`.

А вот что касается описания классов снаружи, это нам в каком сценарии пригодится? Просто мы изначально взяли курс на то, чтобы в компонентах не описывать стили извне, а через просы задавать желаемое поведение. Делать так не очень правильно?

2021-11-11 14:07 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  return <CustomHeading className={`title title_${align}`} {...otherProps}></CustomHeading>;
самый распространенный пример это отступы. 
ты же не сможешь внутри компонента предугадать все варианты отступов, которые могут ему понадобиться. 
по этому просто передаешь в него строчку с классом и снаружи задаешь специфичные стили. а общие стили, типо размера цвета шрифта и тд, которые не зависят от контекста использования, задаются внутри

2021-11-11 15:53 UTC, Verisana commented on src/components/Title/Title.tsx
> +  return <CustomHeading className={`title title_${align}`} {...otherProps}></CustomHeading>;
Понял, спасибо. Я добавил дополнительный `className_`. Без черточки случался конфликт со встроенным `className`:
`Property 'className' does not exist on type 'IntrinsicAttributes'`. Не нашел, как исправить и сделал с черточкой.

2021-11-12 10:22 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  className_ = '',
зачем `_`? просто `className`

2021-11-12 10:23 UTC, bercly0b requested changes

2021-11-12 10:23 UTC, bercly0b commented on src/components/Title/Title.tsx
> +  return <Component className={`title title_${align} ${className_}`} {...otherProps}></Component>;
и тут наверное нужно проверить что className_ есть. а то пробел в итоговый класс добавится.

2021-11-12 10:34 UTC, Verisana commented on src/components/Title/Title.tsx
> +  className_ = '',
По этому поводу ответил выше:
> Понял, спасибо. Я добавил дополнительный className_. Без черточки случался конфликт со встроенным className: `Property 'className' does not exist on type 'IntrinsicAttributes'`. Не нашел, как исправить и сделал с черточкой.

Подозреваю, это из-за того, что из строки создаю компонент, потому что если заменить на `div`, то проблемы нет. Но как это сделать правильно, чтобы не триггерить ошибку, не знаю.

2021-11-12 10:48 UTC, Verisana commented on src/components/Title/Title.tsx
> +  return <Component className={`title title_${align} ${className_}`} {...otherProps}></Component>;
Добавил обработку пробела

2021-11-12 11:25 UTC, merged