Create avatar component
praktikum-game/defence-game pull request #12
Opened 2021-11-10 12:26 UTC by Verisana

Создан компонент Avatar

2021-11-10 12:26 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создать компонент Avatar](https://trello.com/c/ulPxvSTc/41-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-avatar)

2021-11-10 13:47 UTC, diglibum approved these changes

2021-11-10 14:56 UTC, ShvetsovYura commented on src/components/App/App.tsx
> +      <Avatar src="default-avatar.png"></Avatar>
А у нас есть эта картинка? Она отображается?

2021-11-10 15:04 UTC, Verisana commented on src/components/App/App.tsx
> +      <Avatar src="default-avatar.png"></Avatar>
Да, я ее тоже добавил в репозиторий

2021-11-10 15:15 UTC, ShvetsovYura approved these changes

2021-11-10 16:08 UTC, bercly0b commented on src/components/App/App.tsx
> +      <Avatar src="default-avatar.png"></Avatar>
я бы унес default-avatar.png внутрь Avatar и там подставлял как дефолтное значение для src

2021-11-10 16:09 UTC, bercly0b requested changes

2021-11-10 16:09 UTC, bercly0b commented on src/components/Avatar/Avatar.tsx
> +  <img className="avatar" {...props}></img>
ну и тоже про className. с большой вероятностью мы заходим снаружи, где будем использовать этот компонент задать ему какие нибудь отступы или что то еще. 

по этому он должен уметь принимать className и мержить его со своим классом

2021-11-11 09:09 UTC, Verisana commented on src/components/App/App.tsx
> +      <Avatar src="default-avatar.png"></Avatar>
Перенес. Теперь, если ничего не задать, ставится дефолтное значение

2021-11-11 09:14 UTC, Verisana commented on src/components/Avatar/Avatar.tsx
> +  <img className="avatar" {...props}></img>
Добавил новый пропс `additionalClasses`. А мы не будем в таком случае нарушать правило изолированности и независимости блоков по БЭМ? В том числе, названия ведь классов могут стать хаотичными.

2021-11-11 14:02 UTC, bercly0b commented on src/components/Avatar/Avatar.tsx
> +  <img className="avatar" {...props}></img>
нет. принципы бэма это не нарушает.
блок Avatar может одновременно быть элементом блока User (avatar__user)

2021-11-11 14:04 UTC, bercly0b commented on src/components/Avatar/types.ts
> +  additionalClasses?: string[];
а почему это массив? класс же обычно это строка.
представь как ты используешь `div`. ты же в него просто передаешь className="string", давай тут такого же формата придерживаться?

2021-11-11 15:37 UTC, Verisana commented on src/components/Avatar/Avatar.tsx
> +  <img className="avatar" {...props}></img>
Переименовал. Не знал, что такое название является стандартом. Я, наоборот, старался избежать дублирования и путаницы на этой почве :)

2021-11-11 15:40 UTC, Verisana commented on src/components/Avatar/types.ts
> +  additionalClasses?: string[];
Я думал, с массивом удобнее оперировать. Удалять, добавлять классы, нежели со строкой. Исправил на строку

2021-11-12 10:24 UTC, bercly0b approved these changes

2021-11-12 11:23 UTC, merged