Добавил базовую механику игры
praktikum-game/defence-game pull request #21
Opened 2021-11-13 13:16 UTC by ShvetsovYura

Добавил базовую механику игры:
Начало/завершение игры.
Установка защитников, их стрельба, генерация противников. При попадании "пули" противник погибает. При столкновении противника с защитником, он (атакующий) начинает жрать защитника (по 1хп за такт).

2021-11-13 13:18 UTC, ShvetsovYura commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать механику игры на Canvas API](https://trello.com/c/QycvDKRK/10-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%B5%D1%85%D0%B0%D0%BD%D0%B8%D0%BA%D1%83-%D0%B8%D0%B3%D1%80%D1%8B-%D0%BD%D0%B0-canvas-api)

2021-11-13 13:18 UTC, ShvetsovYura commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать состояние начала игры.](https://trello.com/c/jZ1mUxxJ/9-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5-%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%B0-%D0%B8%D0%B3%D1%80%D1%8B)

2021-11-13 13:19 UTC, ShvetsovYura commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать завершение игры](https://trello.com/c/uf1hB5hU/11-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%B3%D1%80%D1%8B)

2021-11-13 18:52 UTC, Verisana reviewed
Спасибо. Сделал большую и кропотливую работу. В целом замечания мелкие. Можно будет на следующем синке обсудить, куда дальше двигаться, в том числе, более архитектурные вопросы.

Я просто думал, что можно реализовать события и различные сценарии через `Event driven approach`. Но не уверен, так вообще делают или нет.

2021-11-13 18:52 UTC, Verisana commented on src/game/FieldGridItem.ts
> +    super(x, y, 100, 100);
Мне кажется, размеры клеток лучше не хардкодить, а вынесту в константу или параметр игры

2021-11-13 18:52 UTC, Verisana commented on src/game/GameField.ts
> +    for (let y = 0; y < gameFieldHeight; y += 100) {
Тогда здесь тоже `100` будет в виде переменной

2021-11-13 18:52 UTC, Verisana commented on src/game/GameField.ts
> +  update() {}
Не очень понял, какая функция на `update`?

2021-11-13 18:52 UTC, Verisana commented on src/game/Game.ts
> +  private _onLoose: Function;
Может, эти функции описать типами? Или заранее неизвестно, как она выглядеть будет?

2021-11-13 18:52 UTC, Verisana commented on src/game/Game.ts
> +  private _onLoose: Function;
Название, наверное, имелось в виду: `_onLose`?

2021-11-13 18:52 UTC, Verisana commented on src/game/Game.ts
> +export default Game;
Вроде без `default` экспортов хотели :)

2021-11-13 18:52 UTC, Verisana commented on src/game/BaseDefender.ts
> +  public get isFIre() {
Опечатка в `isFIre`

2021-11-13 18:52 UTC, Verisana commented on src/game/BaseDefender.ts
> +  private _bullets: Array<BaseBullet>;
Я так понял, тут считаем количество выпущенных пуль и содержащихся на игровом поле?

Такое чувство, что `bullets` тут не должно быть. Я бы думал, что оно должно быть свойством `weapon`, а не защитника. А у защитника должен быть набор из `Items`, которые будут обладать различными свойствами. Это может быть, как оружие, так и просто перк какой-нибудь, дающий, например, очки.

И где-то на уровне объектов игрового поля отслеживать эти `bullets`.

2021-11-14 05:12 UTC, ShvetsovYura commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "warn",
Да, это я забыл вернуть.

2021-11-14 05:13 UTC, ShvetsovYura commented on package.json
> +    "nanoid": "^3.1.30",
в первом модуле его рекомендовал Егор. Говорил, что он проще и быстрее.

2021-11-14 05:14 UTC, ShvetsovYura commented on public/index.html
> +    <div id="portal"></div>
Портал - для рендера элементов вне потока документов, например модальных окон.

2021-11-14 05:15 UTC, ShvetsovYura commented on src/components/Modal/Modal.tsx
> +import React from 'react';
да, это оповещение о статусах игры. Например, о проигрыше или победе.

2021-11-14 05:47 UTC, ShvetsovYura commented on src/pages/GamePage/GamePage.tsx
> +  const [runButtonIsDiabled, setRunButtonIsDiabled] = useState<boolean>(false);
Done.

2021-11-14 05:48 UTC, ShvetsovYura commented on src/game/GameField.ts
> +  update() {}
Испраил.

2021-11-14 05:50 UTC, ShvetsovYura commented on src/game/Game.ts
> +export default Game;
Исправил

2021-11-14 05:51 UTC, ShvetsovYura commented on src/game/BaseDefender.ts
> +  public get isFIre() {
Исправил

2021-11-14 05:55 UTC, ShvetsovYura commented on src/game/BaseDefender.ts
> +  private _bullets: Array<BaseBullet>;
да, задумка такая. Но в текущей реализации - это свойство самого защитника. 
В дальнейшем планируется именно так: "пули" принадлежат оружию, оружие - защитнику. Т.е. для каждого защитника композировать оружие (и другие свойства) как набор свойств.

2021-11-14 05:57 UTC, ShvetsovYura commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "warn",
По поводу событийной модели - я думал об этом. Но пока не придумал =). Здесь, наврено, придется совмещать текущий подход и событийный, т.к. при большом количестве событий их очень сложно отслеживать (нет прямой связи с объектами). Вопрос обсуждения для дальнейшей реализации.

2021-11-14 06:10 UTC, ShvetsovYura commented on src/game/FieldGridItem.ts
> +    super(x, y, 100, 100);
Да, в дальнейшем их надо будет параметризировать. Сейчас норм =)

2021-11-14 06:10 UTC, ShvetsovYura commented on src/game/GameField.ts
> +    for (let y = 0; y < gameFieldHeight; y += 100) {
Да

2021-11-14 06:58 UTC, Verisana commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "warn",
Да, мне тоже кажется, что лучше всего не быть экстремистом и взять лучшее из двух подходов

2021-11-14 07:00 UTC, Verisana commented on public/index.html
> +    <div id="portal"></div>
Немного понял. Но, если не возражаешь, хотел бы еще чуть-чуть помучить вопросами :)
Ты случайно не знаешь, если будем его рендерить в рамках `root`, то к каким проблемам это приведет? Или это вообще не получится сделать в виду каких-то ограничений?

2021-11-15 04:15 UTC, ShvetsovYura commented on src/game/Game.ts
> +  private _onLoose: Function;
Выделил тип для колбэков. Исправил имя колбэка

2021-11-15 05:18 UTC, ShvetsovYura commented on public/index.html
> +    <div id="portal"></div>
[Дока](https://ru.reactjs.org/docs/portals.html#usage)
Можно сделать и без порталов. Есть кейсы с позиционированием, когда применение порталов помогает обойти пробемемы с z-index'ом. Здесь сделано, скорей для показательно/тренировочных целей.

2021-11-15 08:23 UTC, diglibum approved these changes

2021-11-15 14:33 UTC, bercly0b commented on src/components/Modal/Modal.tsx
> +    return <></>;
`return null` кажется было бы правильнее. Fragment это все таки компонент в терминах реакта

2021-11-15 14:37 UTC, bercly0b commented on src/pages/GamePage/GamePage.tsx
> +      setGame(g);
кажется лучше положить переменную `g` в ref, так как она не должна влиять на рендер компонента
ну и дать ей нормально название)

2021-11-15 14:40 UTC, bercly0b commented on src/game/FieldGridItem.ts
> +    super(x, y, 100, 100);
да, я бы тоже сразу же все цифры вынес в константы. потом будет сложнее бегать по проекту и искать их

2021-11-15 14:41 UTC, bercly0b commented on src/game/BaseWeapon.ts
> +//   private fireRate: number;
тут надо удалить лишнее

2021-11-15 14:43 UTC, bercly0b commented on src/game/BaseEnemy.ts
> +img.src = virus;
это бы тоже куда нибудь в конструктор засунуть или в функцию завернуть.
в такой виде у нас будет картинка инитится при заходе на любую страницу, даже если я до игры не дойду

2021-11-15 14:46 UTC, bercly0b commented on src/pages/GamePage/GamePage.tsx
> +      const g = new Game(canvasRef.current, handleLose, handleWin);
я бы объединил 2 коллбека в 1. 
onGameEnd, а в него уже параметром передавать win это или lose
и возможно в будущем у коллбека дополнительные параметры появятся

2021-11-15 14:49 UTC, bercly0b requested changes
в целом мне все нравится. хорошо декомпозировал код.
написал немного замечаний, пройдись по ним пожалуйста
и еще нужно
- прогнать все картинки через какой нибудь оптимизатор, а то 300 КБ это как то слишком)
- сделать в отдельном файле конфиг для игры, вынести туда все цифры и дать им понятное название, за что они отвечают. тогда всем будет понятно куда надо вносить правки если нужно как то сконфигурировать игру.

2021-11-15 16:15 UTC, Verisana commented on public/index.html
> +    <div id="portal"></div>
Окей, понял тебя. Спасибо за уточнения :)

2021-11-15 16:17 UTC, Verisana approved these changes

2021-11-15 19:51 UTC, ShvetsovYura commented on src/components/Modal/Modal.tsx
> +    return <></>;
fix

2021-11-15 20:12 UTC, ShvetsovYura commented on src/pages/GamePage/GamePage.tsx
> +      setGame(g);
fix

2021-11-15 20:13 UTC, ShvetsovYura commented on src/game/BaseWeapon.ts
> +//   private fireRate: number;
fix

2021-11-15 20:13 UTC, ShvetsovYura commented on src/pages/GamePage/GamePage.tsx
> +      const g = new Game(canvasRef.current, handleLose, handleWin);
fix

2021-11-16 06:38 UTC, ShvetsovYura commented
> в целом мне все нравится. хорошо декомпозировал код. написал немного замечаний, пройдись по ним пожалуйста и еще нужно
> 
> * прогнать все картинки через какой нибудь оптимизатор, а то 300 КБ это как то слишком)
> * сделать в отдельном файле конфиг для игры, вынести туда все цифры и дать им понятное название, за что они отвечают. тогда всем будет понятно куда надо вносить правки если нужно как то сконфигурировать игру.

* пожал картинки
* вынес константы в конфиг.

2021-11-16 06:44 UTC, ShvetsovYura commented on src/game/BaseEnemy.ts
> +img.src = virus;
Вынес в отдельное статическое поле. Добавил функцию хелпер по инициализировании картинок. Вынес загрузку ресурсов (картинок в отедльный вспомогательный класс.

2021-11-17 10:31 UTC, bercly0b approved these changes

2021-11-17 10:37 UTC, merged