Pages added
praktikum-game/defence-game pull request #24
Opened 2021-11-14 11:08 UTC by diglibum

Вёрстка страниц:
1) Профиль
2) Редактирование профиля
3) Редактирование пароля
4) Логин
5) Регистрация
Не всё доделано по страницам, но изменений уже довольно много, поэтому открываю PR
Валидацию Страниц профиля и Редактирование Аватара вынесу в отдельные задачи

2021-11-14 11:11 UTC, diglibum commented
![](https://github.trello.services/images/mini-trello-icon.png) [Верстка страниц: Профиль, Логин, Регистрация](https://trello.com/c/huKpYCw2/38-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F)

2021-11-14 11:42 UTC, Verisana commented
Что-то тут не то. Гит в этот ПР добавил еще и докер... Все смешалось. Надо, видимо, залить сначала докер. От рибейзиться по `main`. И тогда надеюсь, что эти изменения уйдут

2021-11-14 13:00 UTC, Verisana commented on src/components/PageContainer/Footer/index.ts
> +export { Button } from './Button';
Неправильный экспорт. Имелся в виду, наверное, `export Footer`

2021-11-14 13:03 UTC, Verisana commented on src/components/PageContainer/Footer/index.ts
> +export { Button } from './Button';
Мне кажется, даже если `Footer` используется только в одном месте, лучше его выставить на один уровень со всеми, а то поначалу вообще непонятно было, откуда он вообще выскочил

2021-11-15 14:42 UTC, ShvetsovYura commented
> Что-то тут не то. Гит в этот ПР добавил еще и докер... Все смешалось. Надо, видимо, залить сначала докер. От рибейзиться по `main`. И тогда надеюсь, что эти изменения уйдут

да, надо #25 подождать...

2021-11-15 17:35 UTC, Verisana reviewed
@diglibum , спасибо за громадную работу со стилями. Я бы, наверное, это к 29 спринту где-то закончил :D

Замечания, вроде, небольшие и, в некоторых случаях, дискуссионные. Могу помочь с некоторыми/всеми, если не хватает времени.

2021-11-15 17:35 UTC, Verisana commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}${className === '' ? className : ' ' + className}`}
Здесь, если не ошибаюсь, мы пришли к тому, чтобы вынести в утилиту или в `bem-cn` делать.
@diglibum 
Я сделаю или ты?

2021-11-15 17:35 UTC, Verisana commented on src/components/Form/Form.tsx
> +      className={`form ${className === '' ? className : ` ${className}`}`}
Тут тоже работу с классами надо будет заменить

2021-11-15 17:35 UTC, Verisana commented on src/components/Header/BackButton.tsx
> +export const BackButton = () => {
А почему мы не выделяем это в отдельный компонент? Или почему бы просто обычный `Button` не использовать для этого? Если не хватает опций, надо, мне кажется, расширить.

2021-11-15 17:35 UTC, Verisana commented on src/components/Header/Header.tsx
> +    className={`header header_${size} ${className === '' ? className : ' ' + className}`}
Тут тоже утилиту поставим. Ну ладно, дальше об этом не пишу. Понятно, что по всем компонентам придется пройтись :)

2021-11-15 17:35 UTC, Verisana commented on src/components/Header/header.css
> +  .avatar {
Аватар разве следует сюда? Он у нас отдельной компонентой идет со своими стилями.

2021-11-15 17:35 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [oldInputValue, setOldInputValue] = useState<string>('');
В `useState` можно не указывать тип, если он совпадает с дефолтным

2021-11-15 17:35 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +    const validationResult = passwordValidator(value);
Кажется, не хватает проверки совпадения значений.

2021-11-15 17:35 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +        <Form className="password-edit-page__form">
Почему не используешь коллбеки в форме? Не понравилось, что я там наворотил? :D
В частности, передавать результаты валидации в параметр `validationResults`.

2021-11-15 17:35 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +            valueChangeCallback={handleOldInput}
Здесь лучше не писать отдельный `handleInput`, так как он есть в `inputValueUpdaterFactory`, который создан для этих однотипных действий. Предлагаю его использовать.

2021-11-15 17:35 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +            valueChangeCallback={handleRepeatInput}
Если использовать `inputValueUpdaterFactory`, то можно уже туда передавать предыдущий пароль, чтобы он проверял на их совпадение:

```
            valueChangeCallback={inputValueUpdaterFactory(
              bindArgsFromN(passwordValidator, 2, passwordValue),
              setRepeatPasswordValidationResult,
              setRepeatPasswordValue,
            )}
```

2021-11-15 17:35 UTC, Verisana commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +const nameInputValidators = [
Здесь тоже валидаторы лучше написать, как на остальных страницах. Если хочешь, могу взяться. Просто думаю, что нет смысла делать одно и то же по-разному.

2021-11-15 17:35 UTC, Verisana commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +  const checkNameInputField = (value: string) => {
Все эти однотипные хендлеры не нужны. Они применяются через `inputValueUpdaterFactory`

2021-11-15 17:35 UTC, Verisana commented on src/pages/ProfilePage/LogoutButton.tsx
> +export const LogoutButton = () => (
Не знаю, правильно или нет то, что пишу, но, может, попытаться этот `Button` тоже попытаться описать через пропсы стандартного `Button`?

2021-11-15 17:35 UTC, Verisana commented on src/pages/ProfilePage/ProfilePage.tsx
> +        <InputField id="first_name" value="Екатерина" type="text" label="Имя" disabled />
Если не ошибаюсь, чтобы `FormData`, правильно извлекал ключи, надо именовать не `id`, а `name`. Вообще, нам эти `name` лучше бы в константу нам вынести, чтобы избежать опечаток в будущем.

2021-11-15 17:35 UTC, Verisana commented on src/utilities/validators/validators.tsx
> +export function emailValidator(value: string): ValidationResult {
Я тут подумал, когда работал с валидаторами. Получилось очень монструозно. Мне кажется, лучше бы регулярками описали все эти требования. Буквально бы в одну строку уложились. И там пару простых ключей добавить `required` и т.п. И все. Валидация стала бы значительно легче. Это я больше для обсуждения и открытия дискуссия
@ShvetsovYura

2021-11-15 17:38 UTC, diglibum commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}${className === '' ? className : ' ' + className}`}
@Verisana - я хочу попрактиковаться с ней )

2021-11-15 17:41 UTC, diglibum commented on src/components/Header/BackButton.tsx
> +export const BackButton = () => {
@Verisana , в отдельный компонент, вроде бы выносится то, что используется во многих местах, а тут у нас эта стрелка в одном месте, мне показалось излишне. С Button не хотелось, так как они уж очень сильно отличаются стилистически и функционально. Но если решим, что нужно в отдельный компонент, вынесу.

2021-11-15 17:42 UTC, diglibum commented on src/components/Header/header.css
> +  .avatar {
@Verisana да, переделаю

2021-11-15 17:44 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +    const validationResult = passwordValidator(value);
@Verisana , помнишь, договаривались, что валидацию сделаю отдельно, так как очень большой PR, но могу сделать и в этом.

2021-11-15 17:45 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +        <Form className="password-edit-page__form">
@Verisana  Пока не вникала, делала только вёрстку

2021-11-15 17:45 UTC, diglibum commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +const nameInputValidators = [
Ответила выше )

2021-11-15 17:46 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +            valueChangeCallback={handleRepeatInput}
Ответила про валидацию выше )

2021-11-15 17:46 UTC, diglibum commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +  const checkNameInputField = (value: string) => {
Ответила про валидацию выше )

2021-11-15 17:48 UTC, diglibum commented on src/pages/ProfilePage/ProfilePage.tsx
> +        <InputField id="first_name" value="Екатерина" type="text" label="Имя" disabled />
Ок.

2021-11-15 18:17 UTC, ShvetsovYura requested changes
Привет. Проделана большая работа. Мы приближаемся к стройному приложению =)
Я пометил наши договоренности (больше для себя) _className util_ 
+ Дал пару коментов

2021-11-15 18:17 UTC, ShvetsovYura commented on src/components/Form/Form.tsx
> +      className={`form ${className === '' ? className : ` ${className}`}`}
_className util_

2021-11-15 18:17 UTC, ShvetsovYura commented on src/components/Header/Header.tsx
> +    className={`header header_${size} ${className === '' ? className : ' ' + className}`}
_className util_

2021-11-15 18:17 UTC, ShvetsovYura commented on src/components/PageContainer/PageContainer.tsx
> +      className === '' ? className : ` ${className}`
_className util_

2021-11-15 18:17 UTC, ShvetsovYura commented on src/components/Title/Title.tsx
> +  const className = className_ === '' ? '' : ` ${className_}`;
_className util_

2021-11-15 18:17 UTC, ShvetsovYura commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [oldInputValue, setOldInputValue] = useState<string>('');
Да, но лично по-мне не принципально, как плюс - можно явно видеть тип. Дискуссионная тема, предлагаю на таких вещах не заострять внимание. Хотя с другой стороны нужно выработать единый код-лайн.

2021-11-15 18:17 UTC, ShvetsovYura commented on src/utilities/validators/validators.tsx
> +export function emailValidator(value: string): ValidationResult {
Давай попробуем регулярки.

2021-11-15 18:23 UTC, Verisana commented on src/components/Header/BackButton.tsx
> +export const BackButton = () => {
Окей, давай оставим. @ShvetsovYura  еще бы выслушать твое мнение на этот счет

2021-11-15 18:28 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [oldInputValue, setOldInputValue] = useState<string>('');
Ну да, мне тоже это не принципиально. Я лишь указал, так как бросилось в глаза :)

2021-11-15 18:28 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +    const validationResult = passwordValidator(value);
Окей, извини. Я, наверное, не так понял этот :)

2021-11-15 18:29 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +        <Form className="password-edit-page__form">
Понял. Все последующие вопросы по этой теме считай не актуальными. Я просто думал, что ты в этой ветке хотела это сделать

2021-11-15 18:31 UTC, Verisana commented on src/utilities/validators/validators.tsx
> +export function emailValidator(value: string): ValidationResult {
Тогда создал себе задачу. Примусь за нее на второй итерации, когда эти изменения вольем, чтобы ничего не сломать и не создать много конфликтов.

2021-11-15 19:13 UTC, diglibum commented on src/pages/ProfilePage/ProfilePage.tsx
> +        <InputField id="first_name" value="Екатерина" type="text" label="Имя" disabled />
@Verisana вспомнила, почему добавила id )) Для того, чтобы при клике на Label у инпута фокус тоже переходил на этот самый инпут, нужно у label указать htmlFor  А для него нужно у инпута указать именно id. Я переделаю, что в инпутах будет добавляться id = name.

2021-11-15 20:16 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [oldInputValue, setOldInputValue] = useState<string>('');
Убрала

2021-11-15 20:58 UTC, diglibum commented on src/components/Header/header.css
> +  .avatar {
@Verisana вспомнила почему разместила здесь )) Это стили для аватара, который находится именно в header (позиционирование и отступы на странице) Ведь может быть ещё аватар на форуме и располагаться он будет иначе. А общие стили прописаны в компоненте Аватар.

2021-11-15 21:45 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +    const validationResult = passwordValidator(value);
Добавила сюда твой вариант с валидацией.

2021-11-15 22:06 UTC, diglibum commented on src/components/Title/Title.tsx
> +  className_,
Тут не получается сделать className, получается конфликт имён, не придумала как решить эту проблему.

2021-11-15 22:13 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +        <Form className="password-edit-page__form">
@Verisana хотела, но передумала ) слишком много итак изменений уже для одного PR

2021-11-16 04:05 UTC, ShvetsovYura approved these changes

2021-11-16 05:54 UTC, Verisana approved these changes
Спасибо, все отлично. Мои замечания в основном - это просто мысли вслух. Если захочешь, можешь пройтись по ним.

2021-11-16 05:54 UTC, Verisana commented on src/components/Title/Title.tsx
> +  className_,
Да, я об этом много раз писал. Тоже не знаю, что делать. Предлагаю пока оставить

2021-11-16 05:54 UTC, Verisana commented on src/pages/LoginPage/LoginPage.tsx
> +import { inputValueUpdaterFactory, InputNames } from '../utilities';
Мне кажется, это надо в `consts.ts`, а не в утилиты, выносить. Но давай пока оставим. Где-нибудь по пути в других ПР изменим

2021-11-16 05:54 UTC, Verisana commented on src/pages/LoginPage/LoginPage.tsx
> +import { inputValueUpdaterFactory, InputNames } from '../utilities';
Я имею в виду `InputNames`

2021-11-16 05:54 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [passwordValue] = useState('OldPass123*');
Я думаю, тут всегда будет изначально пустая строка стоять. У нас не будет информации о пароле юзера. Только хеши :)

2021-11-16 05:54 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [passwordValue] = useState('OldPass123*');
И, честно говоря, не очень понял, зачем эта переменная?

2021-11-16 05:54 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +            valueChangeCallback={inputValueUpdaterFactory(
Мне кажется, тут не нужно проверять на совпадение значений, потому что этого значения у нас нет

2021-11-16 05:54 UTC, Verisana commented on src/pages/utilities/index.ts
> +import { inputValueUpdaterFactory } from './utilities';
Почему бы тут просто сразу 2 экспорта не сделать?

2021-11-16 07:21 UTC, bercly0b commented on src/components/Avatar/Avatar.tsx
> +export const Avatar = ({ src = defaultAvatar, className, ...props }: AvatarProps): JSX.Element => (
я думаю что` : JSX.Element` лишнее, ts должен сам это понимать

2021-11-16 07:22 UTC, bercly0b commented on src/components/Button/button.css
> +  &_default {
👍

2021-11-16 07:23 UTC, bercly0b commented on src/components/Form/Form.tsx
> +  const submitHandler = (e: FormEvent<HTMLFormElement>) => {
`useCallback`

2021-11-16 07:24 UTC, bercly0b commented on src/components/Header/BackButton.tsx
> +      <img src={BackButtonSrc} alt="Назад" onClick={() => navigate(-1)} />
точно onClick должен срабатывать только на иконке? наверное лучше на все кнопке обрабатывать клик.
и почему div, а не button?)

2021-11-16 07:26 UTC, bercly0b commented on src/components/InputField/types.ts
> +  valueChangeCallback?: (value: string, lastValue?: string) => void;
обычно это называют просто `onChange`)

2021-11-16 07:29 UTC, bercly0b commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  });
много похожей логики. можно вынести в хук, что то типа `useFormField`

2021-11-16 07:30 UTC, bercly0b commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +      <div />
зачем этот див?)

2021-11-16 07:31 UTC, bercly0b commented
было бы здорово все svg прогнать через [svgo](https://github.com/svg/svgo)

2021-11-16 07:51 UTC, diglibum commented on src/pages/LoginPage/LoginPage.tsx
> +import { inputValueUpdaterFactory, InputNames } from '../utilities';
@Verisana Да, мне тоже кажется в утилиты не то место, но куда этот const.ts размещать? Он же общий получается

2021-11-16 07:53 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [passwordValue] = useState('OldPass123*');
@Verisana Для того, чтобы при вводе старого пароля можно было его сравнить. Или мы не видим старый пароль и сравнивается он на сервере? Не помню уже что там в апи

2021-11-16 07:54 UTC, diglibum commented on src/pages/utilities/index.ts
> +import { inputValueUpdaterFactory } from './utilities';
Можно, просто люблю такой синтаксис когда всё кучкой экспортируется ))

2021-11-16 07:57 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  const [passwordValue] = useState('OldPass123*');
Убрала

2021-11-16 07:58 UTC, diglibum commented on src/pages/utilities/index.ts
> +import { inputValueUpdaterFactory } from './utilities';
Сделано )

2021-11-16 08:12 UTC, diglibum commented on src/components/Header/BackButton.tsx
> +      <img src={BackButtonSrc} alt="Назад" onClick={() => navigate(-1)} />
исправлено

2021-11-16 08:16 UTC, diglibum commented on src/pages/ProfileEditPage/ProfileEditPage.tsx
> +      <div />
@bercly0b  Для симметрии. Теоретически в правой части header что-то может быть (на странице Профиля там кнопка выхода) У header стоит 
align-items: center;
justify-content: space-between;

для того, чтобы всё было красиво и симметрично, нужен третий элемент ) И это пустой див в данном случае

2021-11-16 08:23 UTC, diglibum commented on src/components/InputField/types.ts
> +  valueChangeCallback?: (value: string, lastValue?: string) => void;
@bercly0b можем это в отдельную задачу вынести если это не критично? Там проблемы с типами возникают, нужно разбираться.

2021-11-16 08:38 UTC, diglibum commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +  });
@bercly0b вынесла в отдельную задачку, если не против.

2021-11-16 08:42 UTC, diglibum commented on src/components/Avatar/Avatar.tsx
> +export const Avatar = ({ src = defaultAvatar, className, ...props }: AvatarProps): JSX.Element => (
@bercly0b убрала во всех компонентах и страницах

2021-11-16 11:33 UTC, Verisana commented on src/pages/LoginPage/LoginPage.tsx
> +import { inputValueUpdaterFactory, InputNames } from '../utilities';
@diglibum 
Да, можно на глобальный уровень

2021-11-16 11:38 UTC, merged