Создал апи, контроллеры и подобие стейта
praktikum-game/defence-game pull request #25
Opened 2021-11-14 17:15 UTC by Verisana

Я создал фпишки и контроллер. Подключил только к регистрации и логину, чтобы не создать много конфликтов в ветке Натальи.

Также получаю предупреждение о том, что у меня где-то `memory leak`. Я так полагаю это из-за корявого редиректа. Без стейта привязанного ко всему приложению, получилось не так, как хотелось. Еще мне не очень нравится то, что передаю в форму слишком много пропсов. По сути там многое можно вытащить на уровень страницы

2021-11-14 17:16 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страницы ошибки 404 / 500 сверстать](https://trello.com/c/Pe2uHUMY/33-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8-404-500-%D1%81%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C)

2021-11-14 17:16 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница входа / сверстать](https://trello.com/c/f6XRSxSq/16-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D1%81%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C)

2021-11-14 17:16 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница регистрации / сверстать](https://trello.com/c/liLuYPFD/18-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%B0%D1%82%D1%8C)

2021-11-14 17:16 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница входа / подключить API](https://trello.com/c/y7VwkuAp/17-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-api)

2021-11-14 17:16 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница регистрации / подключить API](https://trello.com/c/eMEsX9gc/19-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-api)

2021-11-15 06:12 UTC, ShvetsovYura requested changes
Привет. Проделана большая работа. Добавлено много логики. Но есть нексколько моментов для обсуждения/исправления.

2021-11-15 08:45 UTC, diglibum commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}${className === '' ? className : ' ' + className}`}
@ShvetsovYura можешь пояснить вопрос? )

2021-11-15 09:03 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
А ты как предлагаешь сделать? Там имя класса нужно добавить с пробелом.

2021-11-15 09:05 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Азамат делал вот так:

2021-11-15 09:15 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Может добавим  в утилиты что-то вроде такого, чтоб в каждом компоненте не прописывать?
`export function createClassName(className: string, addedClassName: string): string {
  return (addedClassName ? `${className} + ' ' + ${addedClassName}` : className)
}

className = createClassName('footer footer_someClass', ...rest.className );
`

2021-11-15 09:22 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}${className === '' ? className : ' ' + className}`}
@diglibum , на сколько я вижу из кода в словии -  className -  это путсая строка (даже без пробела), это так?

2021-11-15 09:31 UTC, diglibum commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}${className === '' ? className : ' ' + className}`}
@ShvetsovYura этот синтаксис я у кого-то из вас взяла (из старых компонентов). Давай вот тут продолжим наши дебаты? ) https://github.com/praktikum-game/defence-game/pull/25#pullrequestreview-805651641

2021-11-15 09:58 UTC, ShvetsovYura commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Вот смотри, в предпоследней строке (перед `return`) следующее условие: Если className_ (по-умолчанию является пустой строкой, даже без пробела) является пустой строкой, то возвращаем пустую строку, иначе возвращаем строку с именем класса. Я не против такого подхода, но он сбивает с толку и трудно читать становится (в других кусках кода используется вместо className_ - className, и читать становится еще труднее).
Почему не использовать просто `className_` ? ведь если ничего не будет передано в пропс, то возьмется значение по-умолчанию, в противном случае подставится нужная строка. Или может я что-то не понимаю ?

2021-11-15 10:22 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
@ShvetsovYura дело в том, что к className нужно приделать пробел, чтобы классы не слиплись. Поэтому приходится добавлять условие (className ?) (чтобы не было пробела всегда, даже когда он не нужен). Тернарный оператор требует возврата обоих значений - и на true и на false - поэтому приходиться возвращать пустую строку. Выглядит эта запись длинно, да. Азамат пытался вынести в отдельную переменную, чтоб было читабельнее. Я предлагаю сделать отдельную функцию, которая будет конкатенировать эти className-s, так как мы это используем в каждом компоненте, тогда будет выглядеть читабельнее.

2021-11-15 10:32 UTC, ShvetsovYura commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Если использовать bem-cn

`
const b = block('title');
....
return <Component className={b(align).mix(className_)} {...otherPros}></Component>
`
на выходе будет что-то типа 
`
<div class="title title__center classNameFromProps></div>
`
где classNameFromProps - это примиксованое имя класса которое передали свеху в пропс

2021-11-15 10:37 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
classNameProps - это может быть строка вида "class1 class2_some".
b('icon').mix(['one', 'two']); // 'button__icon one two' - а эта утилита требует несколько классов передавать в массиве (правильно понимаю?) А Влад в одном из предыдущих ревью сказал что нельзя массивом (изначально Азамат так и хотел) А если парсить строку в массив предварительно, то читабельности и простоты это не прибавит?

2021-11-15 10:38 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
@bercly0b призываю Влада

2021-11-15 10:39 UTC, ShvetsovYura commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
@diglibum  нет, можно передать просто строку

2021-11-15 10:56 UTC, diglibum commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
@ShvetsovYura выглядит симпатично. Убедил, давай так, сейчас поставлю этот (bem-cn) Одна беда - это PR Азамата, если я внесу исправления в свой Pages Added, тут это не поможет. Можем мы в этом PR оставить этот момент как есть, а когда будем заливать Pages Added, я там везде изменю (иначе утону в конфликтах)?

2021-11-15 11:03 UTC, ShvetsovYura commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Я не против. Здесь @bercly0b должен разрулить (дать зеленый свет)

2021-11-15 11:04 UTC, ShvetsovYura commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
@Verisana давай тогда по остальным замечаниям обсудим, если есть что обсуждать =)

2021-11-15 16:33 UTC, Verisana commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Ору, вот мы начудили, с этими рибейзами :D
Хоть это и является моим ПР, фактически футер писала Наталья. @diglibum  можешь внести изменения у себя. Когда твой вольем, я сделаю рибейз и волью к себе твои изменения. Либо, если хочешь, могу я внести. Но считаю, что это должно быть в ветке `pages_added`, так как он по времени раньше был создан моей ветки

2021-11-15 17:40 UTC, Verisana commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
Когда вольем `pages_added`, я уже тут, если что-то останется, доделаю :)

2021-11-15 17:50 UTC, Verisana commented on src/api/AuthAPI.ts
> +export default new AuthAPI();
А тут такая фигня, что чтобы синглтон экспорт обычным способом сделать нужно было другое название придумывать. Я в `index.ts` экспортировал статичным способом. Но в целом согласен. Порядок есть порядок. Поменял. Но теперь там название с маленькой буквы.

2021-11-15 17:53 UTC, Verisana commented on src/components/App/App.tsx
> +  });
Да, ты прав. Внес изменения

2021-11-15 18:04 UTC, Verisana commented on src/components/Form/Form.tsx
> +    const result = await controllerCallback(formData);
Это фактически методы контроллера. Меняется в зависимости от страницы. Типа на логине мы вызываем `AuthController.login()` на регистрации `AuthController.register()` и т.п. Чтобы для этих однотипных вызовов не городить свои вызовы, передаю нужную функцию в колбек формы, который этим занимается.

2021-11-15 18:05 UTC, Verisana commented on src/components/Form/Form.tsx
> +      className={`form ${className === '' ? className : ` ${className}`}`}
Я так понимаю, это относится к нашей предыдущем теме с классами.

2021-11-15 18:07 UTC, Verisana commented on src/components/Header/BackButton.tsx
> +      <img src={BackButtonSrc} alt="Назад" onClick={() => navigate(-1)} />
@diglibum  обрати, пожалуйста, на этот комментарий, когда будешь вносить изменения в ПР 24. Этот компонент по твоей части.

Но у меня тоже, кажется, не все функции обернуты в `useCallback`. Если найду, тоже поправлю.

2021-11-15 18:09 UTC, Verisana commented on src/components/Title/Title.tsx
> +  className_ = '',
Когда этот компонент, вливали, обсуждали, что возникает какой-то конфликт именно тут с `className` стандартным, если назвать без черточки. Вероятнее всего это из-за того, что новый компонент создается из строки. Как поправить, не нашел. Поэтому выхода два:
1. Либо оставить этот компонент уникальным в названии.
2. Либо все остальные сделать с черточкой.

Ну, или еще глубже поискать корень решения проблемы с коллизией.

2021-11-15 18:11 UTC, Verisana commented on src/components/Title/Title.tsx
> +  const className = className_ === '' ? '' : ` ${className_}`;
Хаха, эта пустая строка не дает тебе жить :D
Вообще, идея родилась из того, что Влад предложил убрать лишний пробел, если ничего не передали. А тернарный оператор должен что-то возвращать. Вот так и возникла эта конструкция

2021-11-15 18:11 UTC, Verisana commented on src/controllers/AuthController.ts
> +export default new AuthController();
Поправил

2021-11-15 18:11 UTC, Verisana commented on src/controllers/UsersController.ts
> +export default new UsersController();
Тоже исправил

2021-11-15 18:18 UTC, Verisana commented on src/pages/HomePage/HomePage.tsx
> +        onClick={AuthController.logout.bind(AuthController)}
Сделано

2021-11-16 11:46 UTC, diglibum approved these changes

2021-11-16 16:17 UTC, ShvetsovYura approved these changes
ok

2021-11-16 16:17 UTC, ShvetsovYura commented on src/controllers/AuthController.ts
> +      console.log(e);
нужно удалить отладочные выводы.

2021-11-16 16:17 UTC, ShvetsovYura commented on src/controllers/AuthController.ts
> +      console.log(e);
удалим console.log

2021-11-17 12:29 UTC, Verisana commented on src/controllers/AuthController.ts
> +      console.log(e);
@ShvetsovYura 
Удалить-то удалим, но что предлагаешь вместо них ставить? У нас нет глобального логгера, куда это можно скидывать, а какие-то действия совершать не требуется.

2021-11-17 14:15 UTC, ShvetsovYura approved these changes
Нормуль =)

2021-11-17 14:21 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Страница пользователя / подключить API](https://trello.com/c/IC2vkGDx/21-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B0-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C-api)

2021-11-17 17:35 UTC, diglibum approved these changes

2021-11-18 16:10 UTC, bercly0b commented on src/api/BaseAPI.ts
> +      baseURL: `${backendUrl}${endpoint}`,
backendUrl тоже бы сделать опциональным. в будущем пригодится
и обычно это называют baseUrl или host

2021-11-18 16:11 UTC, bercly0b commented on src/components/App/App.tsx
> +    authController.userRead().then(() => {});
а зачем такой then?

2021-11-18 16:12 UTC, bercly0b commented on src/components/PageContainer/Footer/Footer.tsx
> +  <div className={`footer ${className === '' ? className : ` ${className}`}`} {...rest}>
да, тут бы утилита наша для классов не помешала бы)

2021-11-18 16:14 UTC, bercly0b commented on src/controllers/AuthController.ts
> +      return true;
а нам от сюда не логичнее было бы пользовательские данные вернуть вместо булеана?

2021-11-18 16:14 UTC, bercly0b commented on src/controllers/AuthController.ts
> +      await this.userRead();
а тут зачем userRead после логаута?

2021-11-18 16:15 UTC, bercly0b commented on src/controllers/AuthController.ts
> +      console.log(response);
да, консоль логи повыпиливать бы..

2021-11-18 16:16 UTC, bercly0b commented on src/pages/LoginPage/LoginPage.tsx
> +  const resetInputValues = () => {
useCallback

2021-11-18 16:18 UTC, bercly0b commented on src/pages/LoginPage/LoginPage.tsx
> +          controllerCallback={authController.login.bind(authController)}
лучше бы тоже в useCallback вынести и сюда ссылку передать

2021-11-18 16:19 UTC, bercly0b commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +          controllerCallback={usersController.updatePassword.bind(usersController)}
https://github.com/praktikum-game/defence-game/pull/25/files#r752406034

2021-11-18 16:21 UTC, bercly0b commented on src/pages/RegisterPage/RegisterPage.tsx
> +  const resetInputValues = () => {
useCallback

2021-11-18 16:21 UTC, bercly0b commented on src/pages/RegisterPage/RegisterPage.tsx
> +  });
https://github.com/praktikum-game/defence-game/pull/25/files#r752407712

2021-11-18 16:40 UTC, Verisana commented on src/api/BaseAPI.ts
> +      baseURL: `${backendUrl}${endpoint}`,
Переименовал и сделал опциональным

2021-11-18 16:40 UTC, Verisana commented on src/components/App/App.tsx
> +    authController.userRead().then(() => {});
Вероятнее всего, осталось после чего-то. Удалил

2021-11-18 16:43 UTC, Verisana commented on src/controllers/AuthController.ts
> +      return true;
Вообще, я думаю, что отсюда ничего не надо возвращать, так как новые данные уже записываются в стор. А оттуда уже обновляются соответствующие компоненты. Мне это нужно было лишь для того, чтобы руками следить за успешностью и неуспешностью запроса. Когда подключим редакс, нужно будет контроллеры отрефакторить немного.

2021-11-18 16:44 UTC, Verisana commented on src/controllers/AuthController.ts
> +      await this.userRead();
Чтобы обновить стор и удалить оттуда юзера. Конечно, по-нормальному нужно экшн запускать, удаляющий юзера, но у меня такого не было. Предлагаю оставить на время, когда подключим редакс.

2021-11-18 16:48 UTC, Verisana commented on src/controllers/AuthController.ts
> +      console.log(response);
@ShvetsovYura 
Раз настаиваете, убрал все консоли по всему проекту. Кроме сервера, который пишет, что слушает такой-то порт

2021-11-18 16:50 UTC, Verisana commented on src/pages/LoginPage/LoginPage.tsx
> +  const resetInputValues = () => {
Сделано

2021-11-18 16:54 UTC, Verisana commented on src/pages/LoginPage/LoginPage.tsx
> +          controllerCallback={authController.login.bind(authController)}
Сделал

2021-11-18 16:56 UTC, Verisana commented on src/pages/PasswordEditPage/PasswordEditPage.tsx
> +          controllerCallback={usersController.updatePassword.bind(usersController)}
Сделано

2021-11-18 17:01 UTC, Verisana commented on src/pages/RegisterPage/RegisterPage.tsx
> +  const resetInputValues = () => {
Сделано

2021-11-18 17:02 UTC, Verisana commented on src/pages/RegisterPage/RegisterPage.tsx
> +  });
https://github.com/praktikum-game/defence-game/pull/25#discussion_r752445197

2021-11-18 18:00 UTC, merged