Create component tests
praktikum-game/defence-game pull request #30
Opened 2021-11-22 14:36 UTC by Verisana

Написал тесты для троих компонент: Button, InputField и Form.
Я тут не делал `snapshot` тестирование и стили не проверял. В идеале, наверное, стоило бы еще изменение классов проверять, но это не укладывается в философию `React Testing Library`.

2021-11-24 06:29 UTC, diglibum approved these changes

2021-11-24 12:42 UTC, bercly0b commented on src/components/InputField/InputField.test.tsx
> +  it('when input changed', () => {
обычно текст в it начинается с глагола
должен посчитать ...
рендерится без ошибок ...
выводит текст ...

2021-11-24 12:43 UTC, bercly0b commented on src/components/InputField/InputField.test.tsx
> +describe('test InputField component', () => {
в describe тоже test наверное лишнее. и так понятно что это тест) 
просто InputField будет понятно)

2021-11-24 12:45 UTC, bercly0b commented on src/components/Button/Button.test.tsx
> +    expect(screen.getByText('Загрузка...')).toHaveTextContent('Загрузка...');
странная формулировка текста) 
типо дай мне текст "загрузка" и проверь что он "загрузка"

тут скорее надо у кнопки взять текст и сравнить его со эталонной строкой

2021-11-24 12:46 UTC, bercly0b requested changes
по хорошему нужно отказаться от использования `screen`, так как тесты модульные, они должны взаимодействовать только с тестируемым модулем (кнопка, инпут и тд)

вот [тут](https://github.com/praktikum-game/defence-game/pull/30/files#r756027644) привел алгоритм как это должно выглядеть

2021-11-25 11:15 UTC, Verisana commented on src/components/InputField/InputField.test.tsx
> +  it('when input changed', () => {
Понял. Исправил по всем тестам, чтобы `it` начинался с глагола

2021-11-25 11:16 UTC, Verisana commented on src/components/InputField/InputField.test.tsx
> +describe('test InputField component', () => {
Точно. Убрал везде

2021-11-25 12:06 UTC, Verisana commented on src/components/Button/Button.test.tsx
> +    expect(screen.getByText('Загрузка...')).toHaveTextContent('Загрузка...');
Согласен, выглядит коряво :)
Я взял по `button` и сравнил тепер

2021-11-25 12:07 UTC, Verisana commented
Убрал везде `screen`. А также заменил в некоторых местах на проверку того, выбрасывает ли поиск по тексту ошибку. Если не выбросил, считаем, что все ок. Но мне кажется, тест стал менее читаемым

2021-11-25 14:01 UTC, merged

2021-11-25 14:18 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Написать тесты на общие используемые компоненты](https://trello.com/c/UzsvCRbU/59-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%BD%D0%B0-%D0%BE%D0%B1%D1%89%D0%B8%D0%B5-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D0%BC%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B)