Base components
praktikum-game/defence-game pull request #5
Opened 2021-11-07 09:52 UTC by ShvetsovYura

Реализовал 2 базовых компонента: 
- Button
- InputField

Добавил валидацию в поле ввода.

Пожалуйста, посмотрите. Выставьте замечания, потому что, наверно нужно (возможно) как-то по другому визуализировать поле ввода.

2021-11-07 09:52 UTC, ShvetsovYura commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cоздать базовый компонент button](https://trello.com/c/lLdm02eY/25-c%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-button)

2021-11-07 09:54 UTC, ShvetsovYura commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cоздать базовый компонент input](https://trello.com/c/3fpYd4Zt/26-c%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%B1%D0%B0%D0%B7%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-input)

2021-11-07 12:22 UTC, ShvetsovYura commented
Наверно, не плохо было бы определить базовые цвета (в переменные), которые потом можно было бы использовать для создания компонент для всего приложнния. Сейчас цвета захардкожены.

2021-11-07 16:18 UTC, diglibum commented on src/components/Button/Button.tsx
> +  size?: 'small' | 'medium' | 'large';
а size где-то используется, или он тоже только для класса?

2021-11-07 16:18 UTC, diglibum commented on src/utilites/InputValidator.ts
> +  static email:ValidateFunction = () => ({ value, message }) => {
`email:ValidateFunction`
Надо настроить линтер, тут пробела нет, а где-то есть =)

2021-11-07 16:18 UTC, diglibum commented on src/components/InputField/InputField.tsx
> +    const { value } = e.target;
const { value } = e.target; 

тут есть пробелы у скобок и знака = а ниже нет =)

2021-11-07 16:18 UTC, diglibum commented on src/components/InputField/InputField.tsx
> +        disabled={disabled}
`disabled={disabled}`
Тут, наверное тоже нужно правило для space-in-brackets и пробелы для знака =

2021-11-07 16:40 UTC, Verisana commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "error"
Хорошее правило. Пусть в нашем коде не будет никаких `any` :)

2021-11-07 18:15 UTC, Verisana requested changes

2021-11-07 18:15 UTC, Verisana commented on src/components/App/App.tsx
> +        validators={[
Мне понравилась система валидации у Юрия. Но я также согласен с твоим уточнением, что можно это дальше запаковать в более крупные куски, чтобы столько параметров не передавать в форму. Можно просто на каждый тип инпута собрать уже готовых валидаторов и выдавать из функции типа `getValidator("email")`, как ты предлагаешь и уже эта функция будет готовить конструкции. В то же время сохраним гибкость.

2021-11-07 18:33 UTC, diglibum commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}`}
Я думала, наоборот отвязать классы от компонента по максимуму ) класс указывать при вызове, а в самом компоненте оставить только button, послушаем что скажет, @bercly0b

2021-11-08 05:02 UTC, ShvetsovYura commented on src/components/Button/button.css
>  .button--primary {
Да, это я запарил, какие разделители ставить. Испарвил

2021-11-08 05:03 UTC, ShvetsovYura commented on src/components/Button/button.css
>  .button--default {
- [ +]

2021-11-08 05:04 UTC, ShvetsovYura commented on src/components/Button/index.tsx
> +export default Button;
Done

2021-11-08 05:19 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +type Props = {
Вынес типы в файлы types.ts

2021-11-08 05:24 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +const viewTypes = {
Я пока не знаю как это красиво затипизировать/сделать слабо-связным. Предлагаю пока оставить так на этой итерации. @Verisana, предлагаю вынести твою идею в отдельную таску и реализовать в следующем PR, если это будет необходимо.

2021-11-08 05:27 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}`}
Судя по тому, как работают UI библиотеки - снаружи пользователь компонента никак не манипулирет классами (стилями) и не знает про них (css-классы) ничего, а использует пропсы компонента, например:
`<Button type="primary">btn</Button>`, а компонент уже отображается сам, как нужно.

2021-11-08 05:28 UTC, ShvetsovYura commented on src/components/InputField/input-field.css
> +.input-field--flex {
Done

2021-11-08 05:32 UTC, ShvetsovYura commented on src/components/App/App.tsx
> +        validators={[
Делать стразу типы, наподобие "email", "text" etc, по-моему не стоит, потому что, например понадобиться текстовое поле с минимальным количеством символов 3 и максимальным количеством - 10, а в другом месте 4-10...
Идея по поводу отдельных пресетов - хорошая, но предлагаю не закапываться в нее на данном этапе. Ведь ее моежно реализовать подздне - необходимый функционал валидация выполняет. @Verisana, можно вынести в отдельную задачу

2021-11-08 05:33 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +  size?: 'small' | 'medium' | 'large';
Отказываемся пока от этого. Спасибо

2021-11-08 05:35 UTC, ShvetsovYura commented on src/utilites/InputValidator.ts
> +  static email:ValidateFunction = () => ({ value, message }) => {
Done

2021-11-08 05:40 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +        disabled={disabled}
вроде норм, это же не деструктуризация. По-мне, так пробелы здесь были бы лишними. 
@Verisana

2021-11-08 05:40 UTC, ShvetsovYura commented on .eslintrc.json
> +    "@typescript-eslint/no-explicit-any": "error"
Да, если сильно приспичит - вклюим :)

2021-11-08 05:40 UTC, ShvetsovYura commented on public/assets/styles/LICENSE.txt
> +Font Awesome Free License
Выпилил.

2021-11-08 05:41 UTC, ShvetsovYura commented on public/index.html
> +    <link rel="stylesheet" href="./assets/styles/css/all.min.css" />
Да, я видел, но не хотел его тащить. Выпилил.

2021-11-08 05:44 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +export default Button;
хм....
Убрал дефолтные импорты из компонетов Button,  InputField (осталось в App). А как тогда экспортится React?
`import React from 'react'`

2021-11-08 05:48 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +        required={required}
Да, вспомнил, убрал. Спасибо.

2021-11-08 06:02 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +  onClick: () => void;
Да, это очень круто, я вспоминл этот урок. Спасибо.
Но что делать, если, например нам не нужно передавать в наш кастомный компонент (например, Button) некоторые атрибуты, например, `className`? 
И еще вопрос: мы хотим, чтобы в наш кастомный Input могли передавать только некторые типы, как быть?
`type Props = {
  type: 'text' | 'password' // но я хочу их написать не руками, а взять как частичые из типов для input
}`

2021-11-08 06:04 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +  onClick: () => void;
Очень хорошая идея - предлагаю вынести в отдельную задачу...
@Verisana

2021-11-08 06:05 UTC, ShvetsovYura commented on src/components/InputField/input-field.css
> +.input-field__error {
Да, так лучше

2021-11-08 06:08 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +    onClick={rest.onClick}
Хорошее замечание. Исправил.
Но тут обратная сторноа - читаемость (явность).

2021-11-08 06:30 UTC, ShvetsovYura commented on src/common/styles/vars.css
> +:root {
Пока не разобрался, как использовать переменные. Нужна будет помощь.

2021-11-08 07:43 UTC, diglibum approved these changes

2021-11-08 09:45 UTC, Verisana commented on src/components/Button/Button.tsx
> +const viewTypes = {
Ок, написал эту задачу в трелло, чтобы не потеряли

2021-11-08 09:53 UTC, Verisana commented on src/components/Button/Button.tsx
> +    className={`button ${viewTypes[view]}`}
Тогда давайте придерживаться такого подхода с манипулированием через пропсы :)
Но я не уверен, что правильно понял Наталью (@diglibum), чтобы утверждать, что мы пришли к консенсусу. Если что, просьба написать о своих возражения.

2021-11-08 09:55 UTC, Verisana commented on src/components/App/App.tsx
> +        validators={[
Я думаю, ее даже не стоит выносить сейчас в отдельную задачу. В целом согласен. Как появится необходимость, реализуем уже, кому попадется. Причем это будет сразу видно, когда в коде повятся большие куски с валидацией.

2021-11-08 09:57 UTC, Verisana commented on src/components/InputField/InputField.tsx
> +        disabled={disabled}
Мне кажется, что так нормально. В официальной документации `React` придерживаются подхода, что нет пробелов в пропсах:
https://reactjs.org/docs/components-and-props.html

2021-11-08 09:58 UTC, Verisana commented on src/common/styles/vars.css
> +:root {
Окей, давай я это вынесу в своем ПР. Я уже делал это в прошлом модуле

2021-11-08 10:04 UTC, Verisana commented on src/components/Button/Button.tsx
> +export default Button;
Он похож на `default` экспорт, но мы не знаем, по каким причинам им пришлось принять такое решение. Возможно, если проект был так запущен, то потом в угоду обратной совместимости не стали ломать. Очень много приложений на них завязано. Либо там еще другие причины, которые не сразу очевидны с нашей колокольни.

Мне аргументы из этих статей показались вполне убедительными :)

2021-11-08 10:09 UTC, Verisana commented on src/components/Button/Button.tsx
> +    onClick={rest.onClick}
Это да. Поэтому даже не знаю, как лучше. Меня любой из вариантов устраивает

2021-11-08 10:10 UTC, Verisana commented on src/components/Button/Button.tsx
> +  onClick: () => void;
Давай возьму в свой ПР, когда буду писать еще компоненты, попробую их по одному стилю прогнать, в том числе, по типизации. Создал себе задачу

2021-11-08 10:15 UTC, Verisana approved these changes

2021-11-08 14:55 UTC, bercly0b commented on src/components/Button/Button.tsx
> +    {(loading && 'Загрузка...') || text}
как то усложнено условие на мой взгляд.
давай более явно `{loading ? 'Загрузка...' : text}` ?

2021-11-08 15:01 UTC, bercly0b commented on src/components/InputField/InputField.tsx
> +    const { value } = e.target;
текущее значение инпута лучше хранить в стейте компонета, а не читать его из дома.
реакт это абстракция для работы с домом. раз уж мы используем эту абстракцию, давайте без необходимости не вылезать из нее)

2021-11-08 15:02 UTC, bercly0b commented on src/components/InputField/InputField.tsx
> +      {<span className="input-field__error-text">{(!error.valid && error.message) || ' '}</span>}
а зачем нам рендерить пустой span? 
давайте будем его добавлять, только если для него есть контент

2021-11-08 15:11 UTC, bercly0b commented on src/components/InputField/InputField.tsx
> +    if (rest.validators) {
правило хоршоей архитектуры - чем глубже компонент, тем меньше у него должно быть ответсвенности и логики.
я предлагаю унести валидацию из инпута и делать ее снаружи.
сейчас у нас ипут валидируется всегда по блюру. могут быть кейсы когда мы захотим валидировать ввод каждого символа например. или когда не нужна валидация совсем.

и тогда, если валидация будет происходить сверху - инпут останется максимально простой.
в него просто будут приходить пропсы isValid и errorText

2021-11-08 17:41 UTC, ShvetsovYura commented on src/components/Button/Button.tsx
> +    {(loading && 'Загрузка...') || text}
Так получилось, наверно, из-за того, что сначала одно условие делал, а потом добавил еще одно =)
Исправил.

2021-11-08 17:43 UTC, ShvetsovYura commented on src/components/Button/types.ts
> +  loading?: boolean;
эмм, в типы кнопки? 
Возможно имелось ввиду типы для InputField? Там это есть.

2021-11-08 18:02 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +    const { value } = e.target;
Релизовал хранение значения в стейте компонента инпута.

2021-11-08 18:05 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +  const checkInputField = (value: string) => {
Давайте, обернул функции, передаваемвые в компоненты в useCallback. А React.memo нужно использовать чтобы получить PureComponent и useCallback работал (или он и так будет работать?)

2021-11-08 18:08 UTC, Verisana commented on src/components/InputField/InputField.tsx
> +    const { value } = e.target;
А нам этот стейт точно в инпуте нужен будет? (я сам не знаю точно) Может, лучше значениеиз из пропса получать, а изменение пробрасывать через коллбек из инпута, чтобы меньше логики в инпут вставить?
Как вот тут:
https://reactjs.org/docs/lifting-state-up.html

2021-11-08 18:34 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +    if (rest.validators) {
Вынес валидацию на уровень родителя. Теперь сам компонент InputField ничего не знает о валидации, а принимает только пропсы, сигнализирующие об ошибке (и текст ошибки)

2021-11-08 19:00 UTC, ShvetsovYura commented on src/components/InputField/InputField.tsx
> +      {<span className="input-field__error-text">{(!error.valid && error.message) || ' '}</span>}
Исправил.

2021-11-09 07:14 UTC, diglibum approved these changes

2021-11-09 07:23 UTC, bercly0b commented on src/components/InputField/InputField.tsx
> +  const checkInputField = (value: string) => {
React.memo тоже нужно. но это немного про другое. он предотвращает лишние рендеры текущего компонента. а useCallback вложенных

2021-11-09 07:23 UTC, bercly0b commented on src/components/Button/types.ts
> +  loading?: boolean;
да, сори)

2021-11-09 07:24 UTC, bercly0b approved these changes

2021-11-09 07:24 UTC, merged