Comments
praktikum-game/defence-game pull request #70
Opened 2022-01-19 20:07 UTC by Verisana

Фух, спасибо Юре за готовые модалки и наработки в `ForumIndex`. Благодарю им худо бедно справился. Добавил комменты +1 уровень вложенности. Можно отвечать только в рут комменты. Получилось криво косо. За пагинацию не пинайте, там все равно в задании этого нет.

Еще подключил аватарки. Они должны работать.

2022-01-19 20:08 UTC, Verisana commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать на клиенте работу с комментариями на форуме](https://trello.com/c/jWtUxWAl/96-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BD%D0%B0-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%83-%D1%81-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D1%8F%D0%BC%D0%B8-%D0%BD%D0%B0-%D1%84%D0%BE%D1%80%D1%83%D0%BC%D0%B5)

2022-01-20 05:44 UTC, ShvetsovYura commented
Привет. У меня почему-то не добавляются коменты =(
+ Не пропадает плашка 
![image](https://user-images.githubusercontent.com/43341468/150280003-f9120480-96cc-476e-b583-61d7bd5d36a5.png)
может эту плашку (загрузки) сделать отдельным компонентом? Наверно так будет правильней

+ Наверно нужно иметь возможность отвечать на ответы (но показывать только коментарий, на который ответили)

2022-01-20 06:11 UTC, ShvetsovYura requested changes
Првет. Большая работа сделана.
Но у меня не завелись коменты (не создаются + не пропадает плашка с загрузкой) - давай попробуем разобраться. 
Еще есть пара замечаний, готов к обсуждению.

2022-01-20 06:11 UTC, ShvetsovYura commented on src/pages/ForumPage/ForumThreadPage/ForumThreadPage.tsx
> +      user: { id: userId, avatar, name },
Наверно будет удобней отдавать с сервера нужную структуру. А дату можно форматировать при выводе.

2022-01-20 06:11 UTC, ShvetsovYura commented on src/pages/ForumPage/components/MessagesList/MessageItem/MessageItem.tsx
> +    <div className={b.mix(className, b({ reply: isReply }))}>
наверно модификатор можно вызвать стразу `b({reply: isReply}).mix(className))`

2022-01-20 06:11 UTC, ShvetsovYura commented on src/server/controllers/ForumCommentsAPI.ts
> +      console.log('test');
.

2022-01-20 06:11 UTC, ShvetsovYura commented on src/server/controllers/ForumCommentsAPI.ts
> +        include: { all: true },
👍

2022-01-20 06:11 UTC, ShvetsovYura commented on src/server/controllers/ForumCommentsAPI.ts
> +          avatar: userData.avatar,
Я в предыдущем  PR вынес эти проверки в отдельную мидлварю. Которая проверяет, если пользователя нет в БД то добавляет его.

2022-01-20 09:13 UTC, Verisana commented on src/components/AppRoutes/routes.tsx
> +                element: <ForumThreadPage />,
Если не ошибаюсь, на последнем синке форум хотели сделать доступным для всех. А писать могут только авторизованные

2022-01-20 09:13 UTC, Verisana commented on src/components/Button/Button.tsx
> +      .mix(className)}
Исправил

2022-01-20 09:15 UTC, Verisana commented on src/pages/ForumPage/ForumThreadPage/ForumThreadPage.tsx
> +    userName: '',
Согласен, что текущее решение совсем тупое. Заменил на имеющийся компонент `Title` для отображения инфы. Заморачиваться с лаудером сейчас вообще нет ни желания, ни сил. Можем оставить на потом, если прям сильно хочется его видеть там :)

2022-01-20 09:17 UTC, Verisana commented on src/server/controllers/ForumCommentsAPI.ts
> +      console.log('test');
Убрал

2022-01-20 09:17 UTC, Verisana commented on src/server/controllers/ForumCommentsAPI.ts
> +          avatar: userData.avatar,
Убрал лишнее и задействовал мидлварю

2022-01-20 09:17 UTC, Verisana commented on src/pages/ForumPage/components/MessagesList/MessageItem/MessageItem.tsx
> +    <div className={b.mix(className, b({ reply: isReply }))}>
Исправил

2022-01-20 09:28 UTC, Verisana commented on src/api/forum-messages/types.ts
> +  };
Заменил на существующий типа `ForumThreadModel`

2022-01-20 09:32 UTC, Verisana commented on src/api/forum-messages/types.ts
> +  userId: number;
Использовал там `CommentAttributes`

2022-01-20 09:46 UTC, Verisana commented on src/pages/ForumPage/ForumThreadPage/ForumThreadPage.tsx
> +      user: { id: userId, avatar, name },
Убрал парсинги все, но при этом не стал обрезать выдачу с сервака. Пусть приходит больше. А тут уже решаем, какая информация нам нужна для использования.

2022-01-20 09:49 UTC, Verisana commented
Все пожаления учел и запушил ветку. Проверь, пожалуйста, еще раз, что все работает (или не работает).

> Наверно нужно иметь возможность отвечать на ответы (но показывать только коментарий, на который ответили)

Я не совсем хорошо себе представляю, как это сделать. Нужно будет рекурсивно парсить коммент, чтобы найти рут. Нам достаточно одного уровня вложенности. Чтобы не смущать, отметил, что это ответ в ветку, а не конкретному человеку. Так выглядит теперь логичнее.

> может эту плашку (загрузки) сделать отдельным компонентом? Наверно так будет правильней

Вынес в имеющийся компонент `Title`

2022-01-20 14:32 UTC, ShvetsovYura approved these changes
Оки-доки.

2022-01-20 14:32 UTC, ShvetsovYura commented on src/server/middlewares/check-user-in-db-middleware.ts
> +            SiteThemeId: 0
Наврно, все-таки `1`, но я предлагаю сделать (или уже сделал - я запутался) `not null`, но при этом `default = 1`  на уровне определения в БД.

2022-01-20 15:05 UTC, Verisana commented on src/server/middlewares/check-user-in-db-middleware.ts
> +            SiteThemeId: 0
Точно. Залагал почему-то. Исправил

2022-01-22 12:54 UTC, bercly0b approved these changes
выглядит ок

2022-01-22 17:54 UTC, Verisana commented on src/components/Avatar/Avatar.tsx
> +    <img className={b.mix(className)} src={src === null ? defaultAvatar : src} {...props}></img>
Тут, короче, такая фигня, что подставляет тогда, когда там `undefined`, а по аватару у нас может прийти `null`, поэтому пришлось и этот случай тоже обработать

2022-01-22 17:55 UTC, merged